[phases.setup] 
cmds = [ 
    "apt-get update", 
    "apt-get install -y libpq-dev gcc", 
] 
 
[phases.install] 
cmds = [ 
    "pip install --upgrade pip", 
    "pip install -r requirements.txt", 
] 
 
[phases.build] 
cmds = [ 
    "python manage.py collectstatic --noinput", 
] 
 
[start] 
cmd = "python manage.py runserver 0.0.0.0:$PORT" 
